name: Build and Sign UWP Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install upm-ci-utils
        run: npm install upm-ci-utils@stable -g --registry https://artifactory.prd.cds.internal.unity3d.com/artifactory/api/npm/upm-npm

      - name: Pack package
        run: upm-ci package pack --package-path .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: HoloLens2-Build
          path: upm-ci~/packages
