name: Build and Sign UWP Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Unity Project
        uses: game-ci/unity-builder@v2
        with:
          projectPath: .
          unityVersion: 2019.1.14f1
          targetPlatform: Universal Windows Platform
          buildTarget: WSAPlayer

      - name: List build files
        run: ls -R build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: HoloLens2-Build
          path: build
