name: Build and Sign UWP Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: microsoft/setup-nuget@v1

      - name: Nuget restore
        run: nuget restore -NonInteractive

      - name: Build solution
        run: msbuild /p:Configuration=Release /p:Platform=x64

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: HoloLens2-Build
          path: bin/x64/Release
